name: cicd-demo
on:
  push:
    branches:
      - '**'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Start build job
        run: echo "Starting the build job."
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Check Java Version
        run: java --version
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew test
      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v4.1.0
        with:
          name: 'test-report'
          path: build/reports/tests/test/*
      - name: Assemble JAR
        run: ./gradlew assemble
      - name: Get Version Number
        run: echo "VERSION=$(./gradlew properties -q | grep "version:" |
          awk '{print $2}')" >> $GITHUB_ENV
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: 'cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar
